# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureReadout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('MAC_address', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('upper_temp_limit', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lower_temp_limit', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='temperaturereadout',
            name='temp_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_registry.TemperatureSensor'),
        ),
    ]
