# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 16:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_registry.Building')),
            ],
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='MAC_address',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La dirección mac no tiene un formato válido', regex='^[a-f0-9:]{17}$')]),
        ),
    ]
