# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_registry', '0002_auto_20170901_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturereadout',
            name='humidity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_registry.Building'),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_registry.Room'),
        ),
    ]
