# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_registry', '0003_auto_20170904_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
