# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_registry', '0004_auto_20170904_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='temp_registry.Building'),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='temp_registry.Room'),
        ),
    ]
