# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_registry', '0005_auto_20170907_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertTimeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.DateTimeField()),
                ('temp_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_registry.TemperatureSensor')),
            ],
        ),
    ]
